GET http://192.168.31.148:8081/v1/accountType/accounts
Accept: application/json

###
GET http://192.168.31.148:8081/v1/accountType
Accept: application/json
Content-Type: application/json

{
  "accountTypeId": 1
}
###

GET http://192.168.31.148:8081/v1/accountType/userRequest
Accept: application/json
Content-Type: application/json

{
  "accountTypeId": 1
}

###


POST http://192.168.31.148:8081/v1/accountType
Accept: application/json
Content-Type: application/json

{
  "type": "PRO Premium",
  "price": 7.81
}
###

PUT http://192.168.31.148:8081/v1/accountType
Accept: application/json
Content-Type: application/json

{
  "accountTypeId": 3,
  "type": "Premium",
  "price": 10
}
###

DELETE http://192.168.31.148:8081/v1/accountType
Accept: application/json
Content-Type: application/json

{
  "accountTypeId": 3
}
###

