GET http://localhost:8080/v1/category
Accept: application/json
Content-Type: application/json

{
  "categoryId": 1
}
###


POST http://localhost:8080/v1/category
Accept: application/json
Content-Type: application/json

{
  "name": "Deportes Extremos Outside 1M"
}
###

PUT http://localhost:8080/v1/category
Accept: application/json
Content-Type: application/json

{
  "categoryId": 8,
  "name": "Ximena"
}
###

PUT http://localhost:8080/v1/category/delete
Accept: application/json
Content-Type: application/json

{
  "categoryId": 1
}
###