GET http://localhost:8080/v1/category
Accept: application/json

###


POST http://localhost:8080/v1/category
Accept: application/json
Content-Type: application/json

{
  "name": "Deportes Extremos Outside"
}
###