GET http://192.168.31.148:8081/v1/category/allCategories
Accept: application/json

###


GET http://192.168.31.148:8081/v1/category/categories?categoryId=1
Accept: application/json

###



POST http://192.168.31.148:8081/v1/category
Accept: application/json
Content-Type: application/json

{
  "name": "JUEGOS",
  "photoId": 1
}
###

PUT http://192.168.31.148:8081/v1/category
Accept: application/json
Content-Type: application/json

{
  "categoryId": 5,
  "name": "Deportes Ext"
}
###

PUT http://192.168.31.148:8081/v1/category/delete
Accept: application/json
Content-Type: application/json

{
  "categoryId": 1
}
###

