GET http://192.168.31.148:8081/v1/chat/chats?userId=1
Accept: application/json

###
GET http://192.168.31.148:8081/v1/chat
Accept: application/json
Content-Type: application/json

{
  "chatId": 2
}
###

GET http://192.168.31.148:8081/v1/chat/request
Accept: application/json
Content-Type: application/json

{
  "chatId": 2
}
###


POST http://localhost:8080/v1/chat
Accept: application/json
Content-Type: application/json

{
  "profile1Id": 9,
  "profile2Id": 8
}
###

DELETE http://localhost:8080/v1/chat
Accept: application/json
Content-Type: application/json

{
  "chatId": 12
}
###