GET http://192.168.1.10:8081/v1/chat/chats?userId=4
Accept: application/json

###
GET http://192.168.1.10:8081/v1/chat/lastChatId
Accept: application/json
Content-Type: application/json
###

GET http://192.168.1.10:8081/v1/chat/request
Accept: application/json
Content-Type: application/json

{
  "chatId": 2
}
###


POST http://192.168.1.10:8081/v1/chat/post
Accept: application/json
Content-Type: application/json

{
  "user1Id": 9,
  "user2Id": 8
}
###

DELETE http://192.168.1.10:8081/v1/chat/delete?chatId=1
Accept: application/json
###