GET http://192.168.31.148:8081/v1/messages/messagesList?userId=10&chatId=5&recUserId=4
Accept: application/json
Content-Type: application/json

###
GET http://192.168.31.148:8081/v1/messages
Accept: application/json
Content-Type: application/json

{
  "messageId": 9
}
###
GET http://192.168.31.148:8081/v1/messages/request
Accept: application/json
Content-Type: application/json

{
"messageId": 9
}
###


POST http://192.168.31.148:8081/v1/messages/post
Accept: application/json
Content-Type: application/json

{
  "chatId": 5,
  "date": "2020-11-24 21:38:10",
  "content": "Why tired?",
  "receiverUserId" : 4,
  "transmitterUserId": 10
}
###


DELETE http://192.168.31.148:8081/v1/messages
Accept: application/json
Content-Type: application/json

{
  "messageId": 9
}