GET http://localhost:8080/v1/reportOptions/reports
Accept: application/json

###

GET http://localhost:8080/v1/reportOptions
Accept: application/json
Content-Type: application/json

{
  "reportOpId": 3
}
###
GET http://localhost:8080/v1/reportOptions/request
Accept: application/json
Content-Type: application/json

{
  "reportOpId": 3
}
###


POST http://localhost:8080/v1/reportOptions
Accept: application/json
Content-Type: application/json

{
  "description": "Insultos"
}

###

PUT http://localhost:8080/v1/reportOptions
Accept: application/json
Content-Type: application/json

{
  "reportOpId": 2,
  "description": "No busca amistad"
}

###
DELETE http://localhost:8080/v1/reportOptions
Accept: application/json
Content-Type: application/json

{
  "reportOpId": 4
}
###