GET http://localhost:8080/v1/report
Accept: application/json
Content-Type: application/json

{
  "reportId": 5
}
###

POST http://localhost:8080/v1/report
Accept: application/json
Content-Type: application/json

{
  "reportOpId": 2,
  "chatId": 7,
  "date": "2020-10-29 22:12:10",
  "reportedUserId": 7,
  "userId": 2
}
###


DELETE http://localhost:8080/v1/report
Accept: application/json
Content-Type: application/json

{
  "reportId": 1
}
###