GET http://localhost:8080/v1/subcategory
Accept: application/json
Content-Type: application/json

{
  "subcategoryId": 1
}
###


POST http://localhost:8080/v1/subcategory
Accept: application/json
Content-Type: application/json

{
  "categoryId": 6,
  "name": "Deportes Sub"
}
###

PUT http://localhost:8080/v1/subcategory
Accept: application/json
Content-Type: application/json

{
  "subcategoryId": 6,
  "name": "Ximena"
}
###

DELETE http://localhost:8080/v1/subcategory
Accept: application/json
Content-Type: application/json

{
  "subcategoryId": 12
}
###