GET http://localhost:8080/v1/subcategory
Accept: application/json
Content-Type: application/json

{
  "subcategoryId": 1
}
###


POST http://localhost:8080/v1/subcategory
Accept: application/json
Content-Type: application/json

{
  "categoryId": 8,
  "name": "Deportes Extremos Outside"
}
###

PUT http://localhost:8080/v1/subcategory
Accept: application/json
Content-Type: application/json

{
  "subcategoryId": 1,
  "name": "Terror"
}
###

DELETE http://localhost:8080/v1/subcategory
Accept: application/json
Content-Type: application/json

{
  "subcategoryId": 3
}
###

GET http://localhost:8080/v1/subcategory/subcategories
Accept: application/json
Content-Type: application/json

{
  "categoryId": 1
}
###