GET http://localhost:8080/v1/subcategory?subcategoryId=1
Accept: application/json

###

GET http://localhost:8080/v1/subcategory/subcategories?categoryId=2
Accept: application/json

###

POST http://localhost:8080/v1/subcategory
Accept: application/json
Content-Type: application/json

{
  "categoryId": 8,
  "name": "Deportes Extremos Outside"
}
###

PUT http://localhost:8080/v1/subcategory
Accept: application/json
Content-Type: application/json

{
  "subcategoryId": 1,
  "name": "Terror"
}
###

PUT http://localhost:8080/v1/subcategory/delete
Accept: application/json
Content-Type: application/json

{
  "subcategoryId": 10
}
###

GET http://localhost:8080/v1/subcategory/1
Accept: application/json

###