GET http://localhost:8080/v1/user
Accept: application/json
Content-Type: application/json

{
  "userId": 1
}
###

GET http://localhost:8080/v1/user/userRequest
Accept: application/json
Content-Type: application/json

{
  "userId": 1
}
###


POST http://localhost:8080/v1/user
Accept: application/json
Content-Type: application/json

{
  "accountTypeId": 2,
  "userTypeId": 2,
  "name": "Rodo",
  "surname": "Mendoza",
  "birthdate": "1992-10-10",
  "gender": 0,
  "email": "ana.mon@gmail.com",
  "password": "12345",
  "userPhoto": "https://concepto.de/wp-content/uploads/2018/10/URL1-e1538664726127.jpg"
}
###

PUT http://localhost:8080/v1/user
Accept: application/json
Content-Type: application/json

{
  "userId": 1,
  "accountTypeId": 1,
  "userTypeId": 1,
  "name": "Alex",
  "surname": "Montaño",
  "birthdate": "1992-10-10",
  "gender": 0,
  "email": "ed.Robles@gmail.com",
  "password": "654321",
  "userPhoto": "https://concepto.de/wp-content/uploads/2018/10/URL1-e1538664726127.jpg"
}
###

DELETE http://localhost:8080/v1/user
Accept: application/json
Content-Type: application/json

{
  "userId": 16
}
###