GET http://192.168.1.10:8081/v1/userSubcategory/userSubcategories?userId=4
Accept: application/json

###

POST http://192.168.1.10:8081/v1/userSubcategory
Accept: application/json
Content-Type: application/json

{
  "userId": 1,
  "subcategoryId": 1
}
###

GET http://192.168.1.10:8081/v1/userSubcategory/userSubMatch?userId=4
Accept: application/json

###

GET http://192.168.1.10:8081/v1/userSubcategory/userSubMatchPremium?userId=4
Accept: application/json