POST http://localhost:8085x/user/addUser
Accept: application/json
Content-Type: application/json

{
  "userName": "Carlos",
  "lastName": "Rengel",
  "email": "rengel123",
  "password": "rengel@gmail.com"
}
###
GET http://localhost:8085/user/allUsers
Accept: application/json